chaincode:
  network:
    ordererLocations:
      orderer0: grpc://192.168.0.176:7050
    peerLocations:
      peer0: grpc://192.168.0.177:7051
      peer1: grpc://192.168.0.178:7051
    eventHubLocations:
      peer0: grpc://192.168.0.177:7053
      peer1: grpc://192.168.0.178:7053
    privateKeyLocation: network/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/c75bd6911aca808941c3557ee7c97e90f3952e379497dc55eb903f31b50abc83_sk
    keyStoreLocation: network/crypto-config/certificates.jks
    mspId: Org1MSP
