# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  couchdb:
    container_name: couchdb
    hostname: couchdb
    extends:
      file: base/docker-compose-base.yaml
      service: couchdb

  peer0.usoft.example.com:
    container_name: peer0.usoft.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.usoft.example.com
    depends_on:
      - couchdb
    extra_hosts:
      - "orderer.example.com:192.168.0.176"
      - "peer0.huasl.example.com:192.168.0.177"
      - "peer0.skypine.example.com:192.168.0.178"
      - "peer0.xinning.example.com:192.168.0.179"
      - "peer0.usoft.example.com:192.168.0.180"
      - "couchdb:192.168.0.180"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.usoft.example.com:7051
      - CORE_PEER_LOCALMSPID=usoftMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usoft.example.com/peers/peer0.usoft.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usoft.example.com/peers/peer0.usoft.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usoft.example.com/peers/peer0.usoft.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usoft.example.com/users/Admin@usoft.example.com/msp
      - LANG=C.UTF-8
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - /root/go/src/github.com/usoftchina/usoftchain-sample/chaincode:/opt/gopath/src/github.com/usoftchina/usoftchain-sample/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.usoft.example.com
    extra_hosts:
    - "orderer.example.com:192.168.0.176"
    - "peer0.huasl.example.com:192.168.0.177"
    - "peer0.skypine.example.com:192.168.0.178"
    - "peer0.xinning.example.com:192.168.0.179"
    - "peer0.usoft.example.com:192.168.0.180"