version: '2'
networks:
  basic: null
services:
    
  orderer.usoftchain.com:
    container_name: orderer.usoftchain.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/usoftchain.com/orderers/orderer.usoftchain.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/usoftchain.com/orderers/orderer.usoftchain.com/tls/:/var/hyperledger/orderer/tls
    networks:
      - basic
    
  peer0.huasl.usoftchain.com:
    container_name: peer0.huasl.usoftchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.huasl.usoftchain.com
      - CORE_PEER_ADDRESS=peer0.huasl.usoftchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.huasl.usoftchain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.huasl.usoftchain.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_LOGGING_PEER=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=huaslMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/huasl.usoftchain.com/peers/peer0.huasl.usoftchain.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/huasl.usoftchain.com/peers/peer0.huasl.usoftchain.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer.usoftchain.com
    networks:
      - basic

  peer0.skypine.usoftchain.com:
    container_name: peer0.skypine.usoftchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.skypine.usoftchain.com
      - CORE_PEER_ADDRESS=peer0.skypine.usoftchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.skypine.usoftchain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.skypine.usoftchain.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_LOGGING_PEER=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=skypineMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/skypine.usoftchain.com/peers/peer0.skypine.usoftchain.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/skypine.usoftchain.com/peers/peer0.skypine.usoftchain.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer.usoftchain.com
    networks:
      - basic

  peer0.xinning.usoftchain.com:
    container_name: peer0.xinning.usoftchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.xinning.usoftchain.com
      - CORE_PEER_ADDRESS=peer0.xinning.usoftchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.xinning.usoftchain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.xinning.usoftchain.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_LOGGING_PEER=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=xinningMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/xinning.usoftchain.com/peers/peer0.xinning.usoftchain.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/xinning.usoftchain.com/peers/peer0.xinning.usoftchain.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer.usoftchain.com
    networks:
      - basic

  peer0.usoft.usoftchain.com:
    container_name: peer0.usoft.usoftchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.usoft.usoftchain.com
      - CORE_PEER_ADDRESS=peer0.usoft.usoftchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.usoft.usoftchain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.usoft.usoftchain.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_LOGGING_PEER=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=usoftMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/usoft.usoftchain.com/peers/peer0.usoft.usoftchain.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/usoft.usoftchain.com/peers/peer0.usoft.usoftchain.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer.usoftchain.com
    networks:
      - basic
    
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.xinning.usoftchain.com:9051
      - CORE_PEER_LOCALMSPID=xinningMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/xinning.usoftchain.com/users/Admin@xinning.usoftchain.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/usoftchina/usoftchain-sample/chaincode/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - basic
    depends_on:
      - orderer.usoftchain.com
      - peer0.huasl.usoftchain.com
      - peer0.skypine.usoftchain.com
      - peer0.xinning.usoftchain.com
      - peer0.usoft.usoftchain.com