# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  kafka1:
    container_name: kafka1
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    extra_hosts:
      - "zookeeper0:192.168.0.176"
      - "zookeeper1:192.168.0.177"
      - "zookeeper2:192.168.0.178"
      - "kafka0:192.168.0.176"
      - "kafka1:192.168.0.177"
      - "kafka2:192.168.0.178"
      - "kafka3:192.168.0.179"